# Generated by Django 5.2.11 on 2026-03-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('interes', models.CharField(choices=[('maquillaje', 'Maquillaje Social'), ('cursos', 'Cursos de Automaquillaje'), ('productos', 'Consulta de Productos')], max_length=50)),
                ('mensaje', models.TextField()),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
