# Generated by Django 5.2.11 on 2026-03-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('foto_antes', models.ImageField(upload_to='galeria/')),
                ('foto_despues', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
